/**
 * Rengifo Gallery Configuration
 * Gallery data for all image collections in the Rengifo project
 */

import { Section } from './types/rengifo'

export const photosContent: Section = {
  title: 'Imaginario Urbano',
  subTitle: 'Imaginario Barrial',
  description: '',
  utilityImages: {
    bg: {
      src: '/fondo1.2.jpg',
      width: 1366,
      height: 1300,
      alt: 'Fondo de la sección de fotos',
    },
  },
  cards: [
    {
      id: 'archivo',
      title: 'Archivo',
      subTitle: 'Fotográfico',
      bgImage: {
        src: '/images/archivo.jpg',
        width: 3307,
        height: 720,
        alt: '',
      },
    },

    {
      id: 'actividades',
      title: 'Fotografías',
      subTitle: 'Actividades',
      bgImage: {
        src: '/images/actividades.jpg',
        width: 3307,
        height: 720,
        alt: '',
      },
    },

    {
      id: 'aereas',
      title: 'Fotografías',
      subTitle: 'Aéreas',
      bgImage: {
        src: '/images/aereas.jpg',
        width: 3307,
        height: 720,
        alt: '',
      },
    },

    {
      id: '3d-exterior',
      title: 'Recorrido 3D',
      subTitle: 'Exterior',
      bgImage: {
        src: '/images/exterior.jpg',
        width: 3307,
        height: 720,
        alt: '',
      },
      disabled: true,
    },

    {
      id: '3d-interior',
      title: 'Recorrido 3D',
      subTitle: 'Interior',
      bgImage: {
        src: '/images/interior.jpg',
        width: 3307,
        height: 720,
        alt: '',
      },
      disabled: true,
    },
  ],
  gallery: {
    photos: {
      id: 'archivo',
      images: [
        {
          src: '/images/archivo/ARCH-01.jpg',
          name: 'Imagen cedida por Mariana Ochoa',
          alt: '',
          width: 0,
          height: 0,
        },
        {
          src: '/images/archivo/ARCH-02.jpg',
          name: 'Imagen cedida por Mariana Ochoa',
          alt: '',
          width: 0,
          height: 0,
        },
        {
          src: '/images/archivo/ARCH-03.jpg',
          name: 'Imagen cedida por Patricia',
          alt: '',
          width: 0,
          height: 0,
        },
        {
          src: '/images/archivo/ARCH-04.jpg',
          name: 'Imagen cedida por Patricia',
          alt: '',
          width: 0,
          height: 0,
        },
        {
          src: '/images/archivo/ARCH-05.jpg',
          name: 'Imagen cedida por Patricia (reverso foto 4)',
          alt: '',
          width: 0,
          height: 0,
        },
        {
          src: '/images/archivo/ARCH-06.jpg',
          name: 'Imagen cedida por Jaqueline Ayala',
          alt: '',
          width: 0,
          height: 0,
        },
        {
          src: '/images/archivo/ARCH-07.jpg',
          name: 'Imagen cedida por Jaqueline Ayala',
          alt: '',
          width: 0,
          height: 0,
        },
        {
          src: '/images/archivo/ARCH-08.jpg',
          name: 'Imagen cedida por Iván Barraza',
          alt: '',
          width: 0,
          height: 0,
        },
        {
          src: '/images/archivo/ARCH-09.jpg',
          name: 'Imagen cedida por Iván Barraza',
          alt: '',
          width: 0,
          height: 0,
        },
        {
          src: '/images/archivo/ARCH-10.jpg',
          name: 'Imagen cedida por Iván Barraza',
          alt: '',
          width: 0,
          height: 0,
        },
        {
          src: '/images/archivo/ARCH-11.jpg',
          name: 'Imagen cedida por Andrea Jorquera',
          alt: '',
          width: 0,
          height: 0,
        },
        {
          src: '/images/archivo/ARCH-12.jpg',
          name: 'Imagen cedida por Andrea Jorquera',
          alt: '',
          width: 0,
          height: 0,
        },
        {
          src: '/images/archivo/ARCH-13.jpg',
          name: 'Imagen cedida por Andrea Jorquera',
          alt: '',
          width: 0,
          height: 0,
        },
        {
          src: '/images/archivo/ARCH-14.jpg',
          name: 'Imagen cedida por Andrea Jorquera',
          alt: '',
          width: 0,
          height: 0,
        },
        {
          src: '/images/archivo/ARCH-15.jpg',
          name: 'Imagen cedida por Andrea Jorquera',
          alt: '',
          width: 0,
          height: 0,
        },
        {
          src: '/images/archivo/ARCH-16.jpg',
          name: 'Imagen cedida por Andrea Jorquera',
          alt: '',
          width: 0,
          height: 0,
        },
        {
          src: '/images/archivo/ARCH-17.jpg',
          name: 'Imagen cedida por Andrea Jorquera',
          alt: '',
          width: 0,
          height: 0,
        },
        {
          src: '/images/archivo/ARCH-18.jpg',
          name: 'Imagen cedida por Rodrigo Valdebenito',
          alt: '',
          width: 0,
          height: 0,
        },
        {
          src: '/images/archivo/ARCH-19.jpg',
          name: 'Imagen cedida por Rodrigo Valdebenito',
          alt: '',
          width: 0,
          height: 0,
        },
        {
          src: '/images/archivo/ARCH-20.jpg',
          name: 'Imagen cedida por Rodrigo Valdebenito',
          alt: '',
          width: 0,
          height: 0,
        },
        {
          src: '/images/archivo/ARCH-21.jpg',
          name: 'Imagen cedida por Rodrigo Valdebenito',
          alt: '',
          width: 0,
          height: 0,
        },
        {
          src: '/images/archivo/ARCH-22.jpg',
          name: 'Imagen cedida por Rodrigo Valdebenito',
          alt: '',
          width: 0,
          height: 0,
        },
        {
          src: '/images/archivo/ARCH-23.jpg',
          name: 'Imagen cedida por Cristián Moya',
          alt: '',
          width: 0,
          height: 0,
        },
        {
          src: '/images/archivo/ARCH-24.jpg',
          name: 'Imagen cedida por Cristián Moya',
          alt: '',
          width: 0,
          height: 0,
        },
        {
          src: '/images/archivo/ARCH-25.jpg',
          name: 'Imagen cedida por Cristián Moya',
          alt: '',
          width: 0,
          height: 0,
        },
        {
          src: '/images/archivo/ARCH-26.jpg',
          name: 'Imagen cedida por Cristián Moya',
          alt: '',
          width: 0,
          height: 0,
        },
        {
          src: '/images/archivo/ARCH-27.jpg',
          name: 'Imagen cedida por Carmen Cortés',
          alt: '',
          width: 0,
          height: 0,
        },
        {
          src: '/images/archivo/ARCH-28.jpg',
          name: 'Imagen cedida por Carmen Cortés',
          alt: '',
          width: 0,
          height: 0,
        },
      ],
    },

    activities: {
      id: 'actividades',
      images: [
        {
          src: '/images/actividades/ACT-01.jpg',
          name: 'Actividad Comunitaria 01',
          alt: '',
          width: 0,
          height: 0,
        },
        {
          src: '/images/actividades/ACT-02.jpg',
          name: 'Actividad Comunitaria 02',
          alt: '',
          width: 0,
          height: 0,
        },
        {
          src: '/images/actividades/ACT-03.jpg',
          name: 'Actividad Comunitaria 03',
          alt: '',
          width: 0,
          height: 0,
        },
        {
          src: '/images/actividades/ACT-04.jpg',
          name: 'Actividad Comunitaria 04',
          alt: '',
          width: 0,
          height: 0,
        },
        {
          src: '/images/actividades/ACT-05.jpg',
          name: 'Actividad Comunitaria 05',
          alt: '',
          width: 0,
          height: 0,
        },
        {
          src: '/images/actividades/ACT-06.jpg',
          name: 'Actividad Comunitaria 06',
          alt: '',
          width: 0,
          height: 0,
        },
        {
          src: '/images/actividades/ACT-07.jpg',
          name: 'Actividad Comunitaria 07',
          alt: '',
          width: 0,
          height: 0,
        },
        {
          src: '/images/actividades/ACT-08.jpg',
          name: 'Actividad Comunitaria 08',
          alt: '',
          width: 0,
          height: 0,
        },
        {
          src: '/images/actividades/ACT-09.jpg',
          name: 'Actividad Comunitaria 09',
          alt: '',
          width: 0,
          height: 0,
        },
        {
          src: '/images/actividades/ACT-10.jpg',
          name: 'Actividad Comunitaria 10',
          alt: '',
          width: 0,
          height: 0,
        },
        {
          src: '/images/actividades/ACT-11.jpg',
          name: 'Actividad Comunitaria 11',
          alt: '',
          width: 0,
          height: 0,
        },
        {
          src: '/images/actividades/ACT-12.jpg',
          name: 'Actividad Comunitaria 12',
          alt: '',
          width: 0,
          height: 0,
        },
        {
          src: '/images/actividades/ACT-13.jpg',
          name: 'Actividad Comunitaria 13',
          alt: '',
          width: 0,
          height: 0,
        },
        {
          src: '/images/actividades/ACT-14.jpg',
          name: 'Actividad Comunitaria 14',
          alt: '',
          width: 0,
          height: 0,
        },
        {
          src: '/images/actividades/ACT-15.jpg',
          name: 'Actividad Comunitaria 15',
          alt: '',
          width: 0,
          height: 0,
        },
      ],
    },

    aerial: {
      id: 'aereas',
      images: [
        {
          src: '/images/aereas/DRON-01.jpg',
          name: 'Vista Aérea 01',
          alt: '',
          width: 0,
          height: 0,
        },
        {
          src: '/images/aereas/DRON-02.jpg',
          name: 'Vista Aérea 02',
          alt: '',
          width: 0,
          height: 0,
        },
        {
          src: '/images/aereas/DRON-03.jpg',
          name: 'Vista Aérea 03',
          alt: '',
          width: 0,
          height: 0,
        },
        {
          src: '/images/aereas/DRON-04.jpg',
          name: 'Vista Aérea 04',
          alt: '',
          width: 0,
          height: 0,
        },
        {
          src: '/images/aereas/DRON-05.jpg',
          name: 'Vista Aérea 05',
          alt: '',
          width: 0,
          height: 0,
        },
        {
          src: '/images/aereas/DRON-06.jpg',
          name: 'Vista Aérea 06',
          alt: '',
          width: 0,
          height: 0,
        },
        {
          src: '/images/aereas/DRON-07.jpg',
          name: 'Vista Aérea 07',
          alt: '',
          width: 0,
          height: 0,
        },
        {
          src: '/images/aereas/DRON-08.jpg',
          name: 'Vista Aérea 08',
          alt: '',
          width: 0,
          height: 0,
        },
        {
          src: '/images/aereas/DRON-09.jpg',
          name: 'Vista Aérea 09',
          alt: '',
          width: 0,
          height: 0,
        },
        {
          src: '/images/aereas/DRON-10.jpg',
          name: 'Vista Aérea 10',
          alt: '',
          width: 0,
          height: 0,
        },
        {
          src: '/images/aereas/DRON-11.jpg',
          name: 'Vista Aérea 11',
          alt: '',
          width: 0,
          height: 0,
        },
        {
          src: '/images/aereas/DRON-12.jpg',
          name: 'Vista Aérea 12',
          alt: '',
          width: 0,
          height: 0,
        },
        {
          src: '/images/aereas/DRON-13.jpg',
          name: 'Vista Aérea 13',
          alt: '',
          width: 0,
          height: 0,
        },
        {
          src: '/images/aereas/DRON-14.jpg',
          name: 'Vista Aérea 14',
          alt: '',
          width: 0,
          height: 0,
        },
      ],
    },
  },
} as const
